import { NextPage } from 'next';
import Head from 'next/head';
import { serverSideTranslations } from 'next-i18next/serverSideTranslations';
import { FaGithub } from 'react-icons/fa';
import { FiMail } from 'react-icons/fi';
import { MdConstruction } from 'react-icons/md'

import PageContent from './components/PageContent';

const About: NextPage = () => {
  return (
    <>
      <Head>
          <title>Chromatacia | About</title>
          <meta name="description" content="Generated by create next app" />
          <link rel="icon" href="/favicon.ico" />
        </Head>
      <PageContent>
        <div className="w-full">
          <div className="flex flex-row justify-between">
            <div>
              <h1>{'About'}</h1>
              <MdConstruction />
            </div>
            <div className="flex flex-col items-end">
              <h2>{'Contact'}</h2>
              <div className="w-full flex flex-row justify-between">
                <a href="https://github.com/elizabethhart"><FaGithub /></a>
                <a href="mailto:elizabethwhart@gmail.com"><FiMail /></a>
              </div>
            </div>
          </div>
        </div>
      </PageContent>
    </>
  );
};

export async function getStaticProps({ locale }) {
  return {
    props: {
      ...(await serverSideTranslations(locale, ['common'])),
      // Will be passed to the page component as props
    },
  };
}

export default About;
