import { useEffect, useState } from 'react';
import { NextPage } from 'next';
import Head from 'next/head';
import axios from 'axios';
import { serverSideTranslations } from 'next-i18next/serverSideTranslations';
import { useTranslation } from 'next-i18next';

import PageContent from './components/PageContent';
import Carousel from './components/Carousel';
import Spinner from './components/Spinner';

const Bookshelf: NextPage = () => {
  const { t } = useTranslation(['common']);
  const [loading, setLoading] = useState<boolean>(true);
  const [currentBooks, setCurrentBooks] = useState<any[]>([]);
  const [recentBooks, setRecentBooks] = useState<any[]>([]);
  const [favoriteBooks, setFavoriteBooks] = useState<any[]>([]);

  const fetchBookshelf = async () => {
    try {
      const {
        data: { current, past, favorites },
      } = await axios.get('/api/bookshelf');

      setCurrentBooks(current);
      setRecentBooks(past);
      setFavoriteBooks(favorites);

      setLoading(false);
    } catch (error) {
      console.log(error);

      setLoading(false);
    }
  };

  useEffect(() => {
    // void fetchBookshelf();
  });

  return (
    <>
      <Head>
        <title>Chromatacia | Bookshelf</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <PageContent>
        <div className="w-full flex flex-col content-center items-center">
          {loading ? (
            <Spinner />
          ) : (
            <>
              <div className="w-full text-center mb-6">
                <h1 className="text-2xl">{t`goodreads-reviews`}</h1>
                <h2 className="text-lg">
                  Check out the books I'm reading on{' '}
                  <a href="https://www.goodreads.com/user/show/89704524-liz-hart">
                    Goodreads
                  </a>
                </h2>
              </div>
              <div className="w-full flex flex-row justify-between">
                {[
                  { name: t`reading`, books: currentBooks },
                  { name: t`just-finished`, books: recentBooks },
                  { name: t`favorites`, books: favoriteBooks },
                ].map((shelf, index) => {
                  console.log(shelf);
                  return (
                    <div key={index}>
                      <div className="w-full text-center mb-6">
                        <h3>{shelf.name}</h3>
                      </div>
                      <div className="w-full flex flex-row justify-center">
                        <Carousel
                          slides={shelf.books.map((book) => {
                            const { title, image_url, authors } = book.book[0];
                            return {
                              image: image_url,
                              title: title,
                              subTitle: authors[0].author[0].name,
                              altText: 'test',
                            };
                          })}
                        />
                      </div>
                    </div>
                  );
                })}
              </div>
            </>
          )}
        </div>
      </PageContent>
    </>
  );
};

export async function getStaticProps({ locale }: { locale: string }) {
  return {
    props: {
      ...(await serverSideTranslations(locale, ['common'])),
      // Will be passed to the page component as props
    },
  };
}

export default Bookshelf;
