// 3rd Party
import { NextPage } from 'next';
import Head from 'next/head';
import { serverSideTranslations } from 'next-i18next/serverSideTranslations';
import { useTranslation } from 'next-i18next';

// UI
import PageContent from '../components/PageContent';
import Header from '../components/Header';
// import Bookshelf from '../pages-components/bookshelf';

const BookshelfPage: NextPage = () => {
  const { t } = useTranslation(['common']);

  return (
    <>
      <Header
        title={t`bookshelf`}
        meta={{ name: 'description', content: 'Generated by create next app' }}
      />
      <PageContent>{/* <Bookshelf /> */}</PageContent>
    </>
  );
};

export async function getStaticProps({ locale }: { locale: string }) {
  return {
    props: {
      ...(await serverSideTranslations(locale, ['common'])),
      // Will be passed to the page component as props
    },
  };
}

export default BookshelfPage;
