// 3rd Party
import { useEffect, useState } from 'react';
import { NextPage } from 'next';
import Head from 'next/head';
import axios from 'axios';
import { serverSideTranslations } from 'next-i18next/serverSideTranslations';
import { useTranslation } from 'next-i18next';

// UI
import PageContent from '../components/PageContent';
import Header from '../components/Header';
import Gallery from '../pages-components/gallery';

const GalleryPage: NextPage = () => {
  const { t } = useTranslation(['common']);

  return (
    <>
      <Header
        title={t`gallery`}
        meta={{ name: 'description', content: 'Generated by create next app' }}
      />
      <PageContent>
        <Gallery />
      </PageContent>
    </>
  );
};

export async function getStaticProps({ locale }: { locale: string }) {
  return {
    props: {
      ...(await serverSideTranslations(locale, ['common'])),
      // Will be passed to the page component as props
    },
  };
}

export default GalleryPage;
