import { useEffect, useState } from 'react';
import { NextPage } from 'next';
import Head from 'next/head';
import axios from 'axios';
import { serverSideTranslations } from 'next-i18next/serverSideTranslations';
import { useTranslation } from 'next-i18next';

import PageContent from './components/PageContent';
import Spinner from './components/Spinner';
import Carousel from './components/Carousel';

const Gallery: NextPage = () => {
  const { t } = useTranslation(['common']);
  const [loading, setLoading] = useState<boolean>(true);
  const [photoset, setPhotoset] = useState<any[]>([]);

  const fetchGallery = async () => {
    try {
      const {
        data: {
          photoset: { photo },
        },
      } = await axios.get('/api/gallery');

      setPhotoset(photo);

      setLoading(false);
    } catch (error) {
      console.log(error);

      setLoading(false);
    }
  };

  useEffect(() => {
    void fetchGallery();
  });

  return (
    <>
      <Head>
        <title>Chromatacia | Gallery</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <PageContent>
        <div className="w-full flex flex-col content-center items-center">
          {loading ? (
            <Spinner />
          ) : (
            <>
              <div className="w-full text-center mb-6">
                <h1>{t`flickr-images`}</h1>
              </div>
              <div className="w-full flex flex-row justify-center">
                <Carousel
                  slides={photoset.map((photo) => ({
                    image: photo.url_o,
                    title: 'test',
                    altText: 'test',
                  }))}
                />
              </div>
            </>
          )}
        </div>
      </PageContent>
    </>
  );
};

export async function getStaticProps({ locale }: { locale: string }) {
  return {
    props: {
      ...(await serverSideTranslations(locale, ['common'])),
      // Will be passed to the page component as props
    },
  };
}

export default Gallery;
