import type { NextPage } from 'next';
import { serverSideTranslations } from 'next-i18next/serverSideTranslations';
import Head from 'next/head';
import { MdConstruction } from 'react-icons/md'

import PageContent from './components/PageContent';

const Home: NextPage = () => {
  return (
    <>
      <Head>
        <title>Chromatacia | Home</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <PageContent>
        <div className="w-full flex flex-row justify-center">
          <div className="text-center">
            <MdConstruction size="300px" />
            <p>under construction</p>
          </div>
        </div>
      </PageContent>
    </>
  );
};

export async function getStaticProps({ locale }) {
  return {
    props: {
      ...(await serverSideTranslations(locale, ['common'])),
      // Will be passed to the page component as props
    },
  };
}

export default Home;
