import type { NextPage } from 'next';
import Head from 'next/head';
import styles from '../styles/Home.module.css';

import PageContent from './components/PageContent';

const Home: NextPage = () => {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <PageContent>
        <div className={styles.container}>content</div>
      </PageContent>
    </>
  );
};

export default Home;
