// 3rd Party
import type { NextPage } from 'next';
import { useTranslation } from 'next-i18next';
import { serverSideTranslations } from 'next-i18next/serverSideTranslations';

// UI
import Header from '../components/Header';
import PageContent from '../components/PageContent';
import { MdConstruction } from 'react-icons/md';

const Home: NextPage = () => {
  const { t } = useTranslation();
  return (
    <>
      <Header
        title={t`home`}
        meta={{ name: 'description', content: 'Generated by create next app' }}
      />
      <PageContent>
        <div className="w-full h-full flex items-center text-white justify-end">
          <div className="flex flex-col items-end">
            <h1 className="text-4xl mb-2">Welcome!</h1>
            <section>
              <div className="flex flex-col w-full justify-center text-center">
                <button
                  className="h-24 w-48 border-2 rounded flex flex-col justify-center items-center"
                  onClick={() =>
                    window.open('https://github.com/elizabethhart', '_blank')
                  }
                  aria-label="under construction"
                >
                  <MdConstruction size="50px" />
                </button>
              </div>
            </section>
          </div>
        </div>
      </PageContent>
    </>
  );
};

export async function getStaticProps({ locale }: { locale: string }) {
  return {
    props: {
      ...(await serverSideTranslations(locale, ['common'])),
      // Will be passed to the page component as props
    },
  };
}

export default Home;
